[general]
import = [ "~/.cache/wal/alacritty.toml" ]

[window]

decorations = "Full"

opacity = 0.7
blur = true

dynamic_padding = true

padding = { x = 10, y = 10}


[font]

normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }

size = 15
